/*
 * BruceHurrican
 * Copyright (c) 2016.
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *
 *    This document is Bruce's individual learning the android demo, wherein the use of the code from the Internet, only to use as a learning exchanges.
 *    And where any person can download and use, but not for commercial purposes.
 *    Author does not assume the resulting corresponding disputes.
 *    If you have good suggestions for the code, you can contact BurrceHurrican@foxmail.com
 *    本文件为Bruce's个人学习android的作品, 其中所用到的代码来源于互联网，仅作为学习交流使用。
 *    任和何人可以下载并使用, 但是不能用于商业用途。
 *    作者不承担由此带来的相应纠纷。
 *    如果对本代码有好的建议，可以联系BurrceHurrican@foxmail.com
 */

package com.brucedaily.database.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import com.brucedaily.database.bean.CostMonth;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "t_CostMonth".
 */
public class CostMonthDao extends AbstractDao<CostMonth, Long> {

    public static final String TABLENAME = "t_CostMonth";

    public CostMonthDao(DaoConfig config) {
        super(config);
    }


    public CostMonthDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "\"t_CostMonth\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE ," + // 0: id
                "\"costDay\" Int NOT NULL ," + // 1: costDay
                "\"costTitle\" String NOT NULL ," + // 2: costTitle
                "\"costDetail\" String," + // 3: costDetail
                "\"costPrice\" String NOT NULL );"); // 4: costPrice
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"t_CostMonth\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CostMonth entity) {
        stmt.clearBindings();

        Long id = entity.id;
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.costDay);
        stmt.bindString(3, entity.costTitle);

        String costDetail = entity.costDetail;
        if (costDetail != null) {
            stmt.bindString(4, costDetail);
        }
        stmt.bindString(5, entity.costPrice);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CostMonth entity) {
        stmt.clearBindings();

        Long id = entity.id;
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.costDay);
        stmt.bindString(3, entity.costTitle);

        String costDetail = entity.costDetail;
        if (costDetail != null) {
            stmt.bindString(4, costDetail);
        }
        stmt.bindString(5, entity.costPrice);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    @Override
    public CostMonth readEntity(Cursor cursor, int offset) {
        CostMonth entity = new CostMonth( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
                cursor.getInt(offset + 1), // costDay
                cursor.getString(offset + 2), // costTitle
                cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // costDetail
                cursor.getString(offset + 4) // costPrice
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, CostMonth entity, int offset) {
        entity.id = cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
        entity.costDay = cursor.getInt(offset + 1);
        entity.costTitle = cursor.getString(offset + 2);
        entity.costDetail = cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3);
        entity.costPrice = cursor.getString(offset + 4);
    }

    @Override
    protected final Long updateKeyAfterInsert(CostMonth entity, long rowId) {
        entity.id = rowId;
        return rowId;
    }

    @Override
    public Long getKey(CostMonth entity) {
        if (entity != null) {
            return entity.id;
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }

//    @Override
//    public boolean hasKey(CostMonth entity) {
//        return entity.getId() != null;
//    }

    /**
     * Properties of entity CostMonth.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property CostDay = new Property(1, int.class, "costDay", false, "costDay");
        public final static Property CostTitle = new Property(2, String.class, "costTitle", false, "costTitle");
        public final static Property CostDetail = new Property(3, String.class, "costDetail", false, "costDetail");
        public final static Property CostPrice = new Property(4, String.class, "costPrice", false, "costPrice");
    }

}
