/*
 * BruceHurrican
 * Copyright (c) 2016.
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 *
 *    This document is Bruce's individual learning the android demo, wherein the use of the code from the Internet, only to use as a learning exchanges.
 *    And where any person can download and use, but not for commercial purposes.
 *    Author does not assume the resulting corresponding disputes.
 *    If you have good suggestions for the code, you can contact BurrceHurrican@foxmail.com
 *    本文件为Bruce's个人学习android的作品, 其中所用到的代码来源于互联网，仅作为学习交流使用。
 *    任和何人可以下载并使用, 但是不能用于商业用途。
 *    作者不承担由此带来的相应纠纷。
 *    如果对本代码有好的建议，可以联系BurrceHurrican@foxmail.com
 */

package com.brucedaily.database.bean;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;
import org.greenrobot.greendao.annotation.NotNull;
import org.greenrobot.greendao.annotation.Property;
import org.greenrobot.greendao.annotation.Unique;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "t_CostMonth".
 */
@Entity(nameInDb = "t_CostMonth")
public class CostMonth {

    /**
     * 自增,无需赋值
     */
    @Id(autoincrement = true)
    @Unique
    public Long id;

    /**
     * 消费日期
     */
    @Property(nameInDb = "costDay")
    public int costDay;

    /**
     * 消费项目标题
     */
    @Property(nameInDb = "costTitle")
    @NotNull
    public String costTitle;

    /**
     * 消费项目详情
     */
    @Property(nameInDb = "costDetail")
    public String costDetail;

    /**
     * 消费项目价格
     */
    @Property(nameInDb = "costPrice")
    @NotNull
    public String costPrice;

    @Generated
    public CostMonth() {
    }

    public CostMonth(Long id) {
        this.id = id;
    }

    @Generated
    public CostMonth(Long id, int costDay, String costTitle, String costDetail, String costPrice) {
        this.id = id;
        this.costDay = costDay;
        this.costTitle = costTitle;
        this.costDetail = costDetail;
        this.costPrice = costPrice;
    }

//    public Long getId() {
//        return id;
//    }
//
//    public void setId(Long id) {
//        this.id = id;
//    }
//
//    public int getCostDay() {
//        return costDay;
//    }
//
//    public void setCostDay(int costDay) {
//        this.costDay = costDay;
//    }
//
//    @NotNull
//    public String getCostTitle() {
//        return costTitle;
//    }
//
//    /**
//     * Not-null value; ensure this value is available before it is saved to the database.
//     */
//    public void setCostTitle(@NotNull String costTitle) {
//        this.costTitle = costTitle;
//    }
//
//    public String getCostDetail() {
//        return costDetail;
//    }
//
//    public void setCostDetail(String costDetail) {
//        this.costDetail = costDetail;
//    }
//
//    @NotNull
//    public String getCostPrice() {
//        return costPrice;
//    }
//
//    /**
//     * Not-null value; ensure this value is available before it is saved to the database.
//     */
//    public void setCostPrice(@NotNull String costPrice) {
//        this.costPrice = costPrice;
//    }

}
